Repository golagola2020/hango-mobile, pull requests merged in 2020-09, with the labels that each got.

#140 [mobile/drinkpage]음료정보 가이드 화면 수정 및 기능 구현
  mobile/hango/app/src/main/java/com/hango/hangoactivity/AddDrinkActivity.java
  mobile/hango/app/src/main/java/com/hango/hangoactivity/DrinkMainActivity.java
  mobile/hango/app/src/main/res/layout/activity_guide_drink_main.xml
Labels: 기능 추가, 모바일, 모바일 UI

#141 [docs] v1.0 리드미 작성 완료
  README.md
  hardware/arduino/README.md
  mobile/README.md
Labels: 문서화, 비개발

#152 [mobile/login]로그인 정보 저장 기능 구현
  mobile/hango/app/src/main/java/com/hango/hangoactivity/InfoActivity.java
  mobile/hango/app/src/main/java/com/hango/hangoactivity/LoginActivity.java
  mobile/hango/app/src/main/res/layout/activity_login.xml
Labels: 기능 추가, 모바일
