Repository golagola2020/hango-mobile, pull requests merged in 2020-08, with the labels that each got.

#1 docs : PR 템플릿 완성
  .github/ISSUE_TEMPLATE/default.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 문서화, 비개발

#3 Initial Setting : 저장소 이전한 이후의 초기 세팅
  arduino/http-client/http-client.ino
  arduino/three_ultraJson_accuracy/three_ultraJson_accuracy.ino
  arduino/three_ultraJson_accuracy/three_ultraJson_accuracy_function.ino
  arduino/wifinina-practice/wifinina-practice.ino
  mobile/login/.gitignore
  mobile/login/.idea/.name
  mobile/login/.idea/codeStyles/Project.xml
  mobile/login/.idea/encodings.xml
  mobile/login/.idea/gradle.xml
  mobile/login/.idea/jarRepositories.xml
  mobile/login/.idea/misc.xml
  mobile/login/.idea/runConfigurations.xml
  mobile/login/.idea/vcs.xml
  mobile/login/app/.gitignore
  mobile/login/app/build.gradle
  mobile/login/app/proguard-rules.pro
  mobile/login/app/src/androidTest/java/com/example/loginactivity/ExampleInstrumentedTest.java
  mobile/login/app/src/main/AndroidManifest.xml
  mobile/login/app/src/main/java/com/example/loginactivity/LoginActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/LoginRequest.java
  mobile/login/app/src/main/java/com/example/loginactivity/MainActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/SignupActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/SignupRequest.java
  mobile/login/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  mobile/login/app/src/main/res/drawable/btn_radius.xml
  mobile/login/app/src/main/res/drawable/ic_add_box_24px.xml
  mobile/login/app/src/main/res/drawable/ic_launcher_background.xml
  mobile/login/app/src/main/res/drawable/main_radius.xml
  mobile/login/app/src/main/res/drawable/main_shadow.xml
  mobile/login/app/src/main/res/font/actor.xml
  mobile/login/app/src/main/res/font/aguafina_script.xml
  mobile/login/app/src/main/res/layout/activity_login.xml
  mobile/login/app/src/main/res/layout/activity_main.xml
  mobile/login/app/src/main/res/layout/activity_signup.xml
  mobile/login/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  mobile/login/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  mobile/login/app/src/main/res/mipmap-hdpi/ic_launcher.png
  mobile/login/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  mobile/login/app/src/main/res/mipmap-mdpi/ic_launcher.png
  mobile/login/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  mobile/login/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  mobile/login/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  mobile/login/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  mobile/login/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  mobile/login/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  mobile/login/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  mobile/login/app/src/main/res/values/colors.xml
  mobile/login/app/src/main/res/values/font_certs.xml
  mobile/login/app/src/main/res/values/preloaded_fonts.xml
  mobile/login/app/src/main/res/values/strings.xml
  mobile/login/app/src/main/res/values/styles.xml
  mobile/login/app/src/test/java/com/example/loginactivity/ExampleUnitTest.java
  mobile/login/build.gradle
  mobile/login/gradle.properties
  mobile/login/gradle/wrapper/gradle-wrapper.jar
  mobile/login/gradle/wrapper/gradle-wrapper.properties
  mobile/login/gradlew
  mobile/login/gradlew.bat
  mobile/login/settings.gradle
Labels: 모바일, 비개발, 아두이노

#27 Mobile/mainpage
  mobile/login/app/src/main/java/com/example/loginactivity/LoginRequest.java
  mobile/login/app/src/main/java/com/example/loginactivity/MainActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/VendingData.java
  mobile/login/app/src/main/java/com/example/loginactivity/VendingListAdapter.java
  mobile/login/app/src/main/res/layout/activity_main.xml
  mobile/login/app/src/main/res/layout/listview_item.xml
Labels: 기능 개선, 기능 추가, 모바일, 모바일 UI

#37 [mobile/userInfo] 회원 탈퇴 기능 구현 완료
  mobile/login/app/src/main/AndroidManifest.xml
  mobile/login/app/src/main/java/com/example/loginactivity/InfoActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/MainActivity.java
  mobile/login/app/src/main/res/drawable/btn_radius.xml
  mobile/login/app/src/main/res/layout/activity_info.xml
  mobile/login/app/src/main/res/layout/activity_main.xml
Labels: 기능 추가, 모바일, 모바일 UI

#46 [mobile/logout] 로그아웃 구현 완료
  mobile/login/app/src/main/java/com/example/loginactivity/InfoActivity.java
Labels: 기능 추가, 모바일

#48 [mobile/userInfoDebug] 서버 통신 테스트를 위한 url 변경
  mobile/login/app/src/main/java/com/example/loginactivity/LoginRequest.java
  mobile/login/app/src/main/java/com/example/loginactivity/MainActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/SignupRequest.java
  mobile/login/app/src/main/java/com/example/loginactivity/UpdateVendingRequest.java
Labels: 모바일

#49 [mobile/userInfoDebug] 리펙토링 완료
  mobile/login/app/src/main/java/com/example/loginactivity/InfoActivity.java
Labels: 기능 개선, 모바일, 버그

#51 [mobile/editSignup] 회원가입시 이메일 입력 및 저장 기능 구현
  mobile/login/app/src/main/java/com/example/loginactivity/SignupActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/SignupRequest.java
  mobile/login/app/src/main/res/layout/activity_signup.xml
Labels: 기능 추가, 모바일, 모바일 UI

#52 [mobile/updateInfo] 회원 정보 변경 화면 구현
  mobile/login/app/src/main/AndroidManifest.xml
  mobile/login/app/src/main/java/com/example/loginactivity/InfoActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/InfoUpdateActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/LoginActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/SignupActivity.java
  mobile/login/app/src/main/res/layout/activity_info_update.xml
  mobile/login/app/src/main/res/layout/activity_login.xml
  mobile/login/app/src/main/res/layout/activity_signup.xml
Labels: 기능 추가, 모바일 UI, 서버

#53 [mobile/mainpage]메인화면 ListView 기능별 객체화 및 버그 수정
  mobile/login/app/src/main/java/com/example/loginactivity/MainActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/VendingData.java
  mobile/login/app/src/main/java/com/example/loginactivity/VendingListAdapter.java
Labels: 기능 개선, 모바일, 버그

#56 [rasp/serial] 초음파 센서의 센싱정보 라즈베리파이로 전송
  arduino/four_ultra/four_ultra.ino
  arduino/four_ultra/four_ultra_function.ino
  arduino/four_ultrasonic/four_ultrasonic.ino
  arduino/four_ultrasonic/four_ultrasonic_py.py
Labels: 기능 추가, 라즈베리파이, 아두이노

#62 [Server/fix updated info json] 회원 정보 수정의 JSON 교환 형식 변경 완료
  mobile/login/app/src/main/java/com/example/loginactivity/InfoUpdateActivity.java
Labels: 기능 개선, 모바일

#63 [Mobile/vendingupdatepage]자판기 수정 UI 및 기능 수정
  mobile/login/app/src/main/java/com/example/loginactivity/LoginRequest.java
  mobile/login/app/src/main/java/com/example/loginactivity/MainActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/UpdateVendingActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/UpdateVendingRequest.java
  mobile/login/app/src/main/res/layout/activity_update_vending.xml
Labels: 기능 개선, 모바일, 모바일 UI

#64 [mobile/mainpage]ListView item 클릭 이벤트 오류 수정
  mobile/login/app/src/main/java/com/example/loginactivity/MainActivity.java
  mobile/login/app/src/main/res/layout/activity_main.xml
  mobile/login/app/src/main/res/layout/listview_item.xml
Labels: 모바일, 버그

#73 [Hardware/refectoring] 하드웨어 코드 리펙토링
  arduino/four_ultrasonic/four_ultrasonic.ino
  arduino/four_ultrasonic/four_ultrasonic_py.py
Labels: 기능 개선, 라즈베리파이, 아두이노

#74 [hardware/refectoring] 라즈베리파이 오타 수정
  arduino/four_ultrasonic/four_ultrasonic_py.py
Labels: 기능 개선, 라즈베리파이

#78 [hardware/refectoring] 라즈베리파이 기능 개선
  arduino/rasp.py
Labels: 기능 개선, 라즈베리파이

#79 [Mobile/drinkpage]음료 수정 팝업창 구현
  mobile/login/app/src/main/java/com/example/loginactivity/DrinkMainActivity.java
Labels: 기능 추가, 모바일

#80 [rasp/requestDrinksUpdate] 판매된 음료 정보 차감 함수 구현
  arduino/rasp.py
Labels: 기능 추가, 라즈베리파이

#83 [hardware/refectoring] 음료 정보 요청 기능 개선
  arduino/rasp.py
Labels: 기능 개선, 라즈베리파이

#84 [rasp/speakReceivedDrinks] speak() 함수 구현 완료
  arduino/rasp.py
Labels: 기능 개선, 기능 추가, 라즈베리파이

#86 [Mobile/mainpage]자판기 검색기능 구현 및 버그 수정
  mobile/login/app/src/main/java/com/example/loginactivity/DrinkListAdapter.java
  mobile/login/app/src/main/java/com/example/loginactivity/DrinkMainActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/InfoActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/InfoUpdateActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/MainActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/SignupRequest.java
  mobile/login/app/src/main/java/com/example/loginactivity/VendingListAdapter.java
  mobile/login/app/src/main/res/layout/activity_main.xml
Labels: 기능 개선, 기능 추가, 모바일, 버그

#87 [Mobile/drinkpage]음료정보 GridView 오류 수정
  mobile/login/app/src/main/java/com/example/loginactivity/DrinkItem.java
  mobile/login/app/src/main/java/com/example/loginactivity/DrinkListAdapter.java
  mobile/login/app/src/main/java/com/example/loginactivity/DrinkMainActivity.java
  mobile/login/app/src/main/res/layout/activity_main.xml
  mobile/login/app/src/main/res/layout/drink_item.xml
Labels: 모바일, 버그

#90 [rasp/speakRecievedDrinks]서버에게 전달받은 음료 데이터를 스피커로 출력.
  arduino/rasp.py
Labels: 라즈베리파이

#97 [hardware/refectoring] 아두이노 코드 리펙토링
  arduino/real_auto_hango/real_auto_hango.ino
  arduino/아두이노 주석
Labels: 기능 개선, 아두이노

#98 [hardware/refectoring]아두이노 코드 리펙토링, break추가 완료
  arduino/real_auto_hango/real_auto_hango.ino
Labels: 기능 개선, 아두이노

#99 [rasp/multiProcess] 멀티 프로세싱 테스트 구문 구현 완료
  arduino/asyncTest.py
Labels: 라즈베리파이, 테스트

#100 [rasp/multiProcessing] 멀티프로세싱 라즈베리파이 적용 완료
  arduino/asyncTest.py
  arduino/rasp.py
Labels: 기능 추가, 라즈베리파이

#103 [rasp/refectoring] 라즈베리파이 리펙토링 완료 및 불피요한 파일 삭제
  arduino/asyncTest.py
  arduino/four_ultrasonic/four_ultrasonic.ino
  arduino/four_ultrasonic/four_ultrasonic_py.py
  arduino/http-client/http-client.ino
  arduino/rasp.py
  arduino/wifinina-practice/wifinina-practice.ino
  arduino/아두이노 주석
  hardware/arduino.ino
  hardware/raspberry.py
Labels: 기능 개선, 라즈베리파이

#104 [rasp/speakSoldout] 품절 정보 출력 기능 구현 완료
  hardware/raspberry.py
Labels: 기능 추가, 라즈베리파이

#105 [rasp/speakSoldout] 오타 수정
  hardware/raspberry.py
Labels: 기능 개선, 라즈베리파이, 버그

#106 [mobile/mainpage]자판기 수정 실시간 갱신 기능 구현
  mobile/login/app/src/main/java/com/example/loginactivity/MainActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/UpdateVendingActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/VendingListAdapter.java
Labels: 기능 추가, 모바일

#113 [Mobile/drinkpage] 음료페이지 기능 추가 및 수정
  mobile/login/app/src/main/java/com/example/loginactivity/AddDrinkActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/DrinkItem.java
  mobile/login/app/src/main/java/com/example/loginactivity/DrinkListAdapter.java
  mobile/login/app/src/main/java/com/example/loginactivity/DrinkMainActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/MainActivity.java
Labels: 기능 추가, 모바일

#114 [mobile/drinkpage]음료 refresh 버튼 추가
  mobile/login/app/src/main/java/com/example/loginactivity/DrinkMainActivity.java
  mobile/login/app/src/main/res/layout/activity_drink_main.xml
Labels: 모바일 UI

#115 [mobile/mainpage]자판기 ListView code refactoring
  mobile/login/app/src/main/java/com/example/loginactivity/MainActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/UpdateVendingActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/VendingListAdapter.java
Labels: 모바일

#116 [Mobile/drinkpage]음료정보 화면 기능 추가 및 수정
  mobile/login/app/src/main/AndroidManifest.xml
  mobile/login/app/src/main/java/com/example/loginactivity/AddDrinkActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/DrinkListAdapter.java
  mobile/login/app/src/main/java/com/example/loginactivity/DrinkMainActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/DrinkRefreshAcceptActivity.java
  mobile/login/app/src/main/res/layout/activity_drink_refresh_accept.xml
Labels: 기능 추가, 모바일

#120 [client/docs]READEME 1차 작업
  README.md
Labels: 라즈베리파이, 문서화, 아두이노

#122 [Docs] root README.md 작성 완료
  README.md
  hardware/arduino/README.md
  hardware/arduino/main.ino
  hardware/raspberry/README.md
  hardware/raspberry/main.py
  mobile/README.md
Labels: 문서화, 비개발

#126 [Mobile/drinkpage]음료정보 페이지 UI 수정 및 code refactoring
  mobile/login/app/src/main/AndroidManifest.xml
  mobile/login/app/src/main/java/com/example/loginactivity/DrinkListAdapter.java
  mobile/login/app/src/main/java/com/example/loginactivity/DrinkMainActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/DrinkRefreshAcceptActivity.java
  mobile/login/app/src/main/java/com/example/loginactivity/UpdateDrinkActivity.java
  mobile/login/app/src/main/res/drawable/btn_accept.xml
  mobile/login/app/src/main/res/drawable/btn_deny.xml
  mobile/login/app/src/main/res/drawable/btn_radius.xml
  mobile/login/app/src/main/res/drawable/ic_arrow_back.xml
  mobile/login/app/src/main/res/drawable/ic_drink_add.xml
  mobile/login/app/src/main/res/drawable/ic_info.xml
  mobile/login/app/src/main/res/drawable/ic_refresh.xml
  mobile/login/app/src/main/res/layout/activity_add_drink.xml
  mobile/login/app/src/main/res/layout/activity_drink_main.xml
  mobile/login/app/src/main/res/layout/activity_drink_refresh_accept.xml
  mobile/login/app/src/main/res/layout/activity_update_drink.xml
  mobile/login/app/src/main/res/layout/add_drink_item.xml
Labels: 기능 개선, 모바일, 모바일 UI

#127 [Mobile/mainpage]메인 화면 UI 수정
  mobile/login/app/src/main/java/com/example/loginactivity/MainActivity.java
  mobile/login/app/src/main/res/drawable/ic_delete.xml
  mobile/login/app/src/main/res/drawable/ic_edit.xml
  mobile/login/app/src/main/res/drawable/ic_menu.xml
  mobile/login/app/src/main/res/drawable/main_shadow.xml
  mobile/login/app/src/main/res/layout/activity_main.xml
  mobile/login/app/src/main/res/layout/activity_update_vending.xml
Labels: 모바일, 모바일 UI

#128 [mobile/mainpage]메인화면 로고 생성 및 UI 수정
  mobile/login/app/src/main/java/com/example/loginactivity/MainActivity.java
  mobile/login/app/src/main/res/drawable/ic_hango_logo.xml
  mobile/login/app/src/main/res/drawable/main_shadow.xml
  mobile/login/app/src/main/res/layout/activity_main.xml
Labels: 모바일, 모바일 UI

#129 [mobile/login]로그인 화면 UI 수정
  mobile/login/app/src/main/res/drawable-v24/ic_hango_logo_white.xml
  mobile/login/app/src/main/res/drawable/ic_hango_logo_blue.xml
  mobile/login/app/src/main/res/layout/activity_login.xml
  mobile/login/app/src/main/res/layout/activity_main.xml
Labels: 모바일, 모바일 UI

#133 [mobile/drinkpage]뒤로가기 기능 구현
  mobile/hango/app/src/main/java/com/hango/hangoactivity/DrinkMainActivity.java
Labels: 기능 추가, 모바일

#134 [mobile/login]로그인화면 UI 수정
  mobile/hango/app/src/main/res/drawable/ic_id.xml
  mobile/hango/app/src/main/res/drawable/ic_password.xml
  mobile/hango/app/src/main/res/layout/activity_login.xml
Labels: 모바일 UI

#137 [mobile/mainpage]자판기 ListView UI 수정
  mobile/hango/app/src/main/res/drawable/main_shadow.xml
Labels: 모바일, 모바일 UI
